CREATE DATABASE IF NOT EXISTS msauth_db;
CREATE DATABASE IF NOT EXISTS produit_db;
CREATE DATABASE IF NOT EXISTS stock_db;
CREATE DATABASE IF NOT EXISTS commande_db;
CREATE DATABASE IF NOT EXISTS fournisseur_db;
CREATE DATABASE IF NOT EXISTS notif_db;
