spring.application.name=Gateway
server.port=7777

spring.main.web-application-type=reactive
spring.cloud.config.enabled=false

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true


eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# Actuator
management.endpoints.web.exposure.include=*



# ======== ROUTES MANUELLES =============

# --- FOURNISSEUR ---
spring.cloud.gateway.server.webflux.routes[0].id=FOURNISSEUR-SERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=lb://msfournisseur
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/fournisseurs/**

# --- STOCK ---
spring.cloud.gateway.server.webflux.routes[1].id=STOCK-SERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=lb://msstock
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/stock/**

# --- PRODUIT ---
spring.cloud.gateway.server.webflux.routes[2].id=PRODUIT-SERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=lb://msproduit
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/produits/**

# --- COMMANDE ---
spring.cloud.gateway.server.webflux.routes[3].id=COMMANDE-SERVICE
spring.cloud.gateway.server.webflux.routes[3].uri=lb://mscommande
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/commandes/**

# --- NOTIFICATION ---
spring.cloud.gateway.server.webflux.routes[4].id=NOTIFICATION-SERVICE
spring.cloud.gateway.server.webflux.routes[4].uri=lb://msnotif
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/notifications/**

# --- AUTH ---
spring.cloud.gateway.server.webflux.routes[5].id=AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[5].uri=lb://msauth
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/msauth/**

